
name: Blog posts helper

on: 
  push:
    branches:
      - master____

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python3 sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: install dependencies
        run: |
            sudo apt -y install graphviz
            python -m pip install --upgrade pip
            pip install joblib requests tqdm 
        
      # - name: update drafts into posts
      #   run: python format.py
        
